### ISSUE TITLE
`/topics/eval-intro.md` has several issues

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#102]
In review before publishing #91, `eval-intro.md` has several issues:

- Has several references that should be primary/replica
- Links to an unknown hash `docs/topics/protocol#resp-arrays` (probably should be `#arrays`)
- Weird bang in front of `!SCRIPT` in heading (looks like this may have been some sort of now dead markup)
- Has references to old versions`In Redis OSS 5.0, effects replication became the default mode.`, `Starting with Redis OSS 3.2, it is possible to select an alternative replication method.`, `starting with Redis OSS 5.0`

**Comment by zuiderkwast** [comment]
> * Weird bang in front of `!SCRIPT` in heading (looks like this may have been some sort of now dead markup)

The "Weird bang" is from the old redis website. All commands in backticks were automatically linked to the command doc pages. The bang prevents this from being interpreted as the SCRIPT command.

I kept it intentionally because I assumed you know about it and I thought we may want to keep this behaviour. I don't like it though since it's kind of hidden secret markup.

It is good to have links between the topics pages and the command pages though, but not every occurrence needs to be linked. How about we link explicitly to the command on the first occurrence on each page?

A script could update all the pages and occurrences of `!STUFF` throught the pages. (The bangs are present in the replies JSON and commands JSON files too btw.)
