### ISSUE TITLE
`/topics/installation.md` references exploit venerable below Redis 3.2 and has instructions for `init.d`

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#108]
In pre-publishing review (#91), the following issues were noted:

> Note that a Valkey instance exposed to the internet without any security [is very simple to exploit](http://antirez.com/news/96), so make sure you understand the above and apply at least a firewall layer.

The firewall is good advice, but the exploit outlined is fixed in 3.2+, this advice should probably be updated to made relevant for 2024/Valkey.

> A proper install using an init script is strongly recommended.
Note: The available packages for supported Linux distributions already include the capability of starting the Valkey server from /etc/init.

This section proceeds to go into quite a bit of detail in creating a `init.d` script. In 2024, would be we better off providing instructions for a service?

**Comment by zuiderkwast** [comment]
> Note that a Valkey instance exposed to the internet without any security [is very simple to exploit](http://antirez.com/news/96), so make sure you understand the above and apply at least a firewall layer.

I'm deleting this.

> This section proceeds to go into quite a bit of detail in creating a init.d script. In 2024, would be we better off providing instructions for a service?

I agree. I'm changing this a bit, but I don't know by heart how to set up a systemd service. I'll just write that Valkey supports systemd and that this document was written before systemd was widely adapted. I see now on this page https://en.wikipedia.org/wiki/Systemd#Adoption that there are some distros that don't use systemd and Valkey indeed runs on embedded machines so I think I'll keep the init.d stuff around.

I'll also

* refer to ACL (acl.md) as the primary way to set up AUTH, rather than requirepass.
* refer to proper TLS (encryption.md) instead of using some 3rd party TLS tunneling software.
