### ISSUE TITLE
`/topics/lru-cache.md` has old references

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#114]
In pre-publishing review (#91), I discovered the following issue with `/topics/lru-cache.md`:

> However, since Redis OSS 3.0 the algorithm was improved to also take a pool of good candidates for eviction. 

And then proceeds to illustrate how Redis 2.8 and 3.0 compare. These are very old, irrelevant versions.

> The new LFU mode... Starting with Redis OSS 4.0....

These sections should be refactored to talk about the current state and now provide version comparisons for years old versions of another project.

**Comment by zuiderkwast** [comment]
Removing references to old Redis OSS.

Removing the comparison between 2.8 and 3.0 but keeping the graphics and explanation, due to the lack of an updated version of this.

Adding a parenthesis "(The LRU algorithm hasn't changed considerably since this test was performed, so the performance of Valkey is similar in this regard.)".

Correction "expire" => "evict" (a few occurrences)

Changing references like "with the expire field set to true" to "with a time-to-live (TTL) set" or similar. (There is no expire boolean. Only a timestamp.)
