### ISSUE TITLE
`/topics/modules-blocking-ops.md` has outdated info and misnamed projects

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#120]
In pre-publishing review (#91) I noticed a few things with `/topics/modules-blocking-ops.md`

Code blocks don't use backticks nor specify a language for syntax highlighting.

> An example of this approach is the [Neural Valkey module](https://github.com/antirez/neural-redis) where neural networks are trained in different threads while the user can still execute and inspect their older versions.

This links to Neural Redis and should be named correctly. Additional this particular module hasn't been touched in many years and might not be a good example of a module, if it work at all in Valkey.

> Future work
An API is work in progress right now in order to allow Valkey modules APIs to be called in a safe way from threads, so that the threaded command can access the data space and do incremental operations.
There is no ETA for this feature but it may appear in the course of the Redis OSS 4.0 release at some point.

This is outdated.

**Comment by zuiderkwast** [comment]
> Code blocks don't use backticks nor specify a language for syntax highlighting.

I fix.

> This links to Neural Redis and should be named correctly.

I fix.

> Additional this particular module hasn't been touched in many years and might not be a good example of a module, if it work at all in Valkey.

I'm going to keep this. It serves the purpose of illustrating how background threads can be used while serving commands. Anyone who wants to implement this can have great help from reading the source code of this module. It probably works in Valkey too (since we hardly ever break anything) but that's not the point.

> Future work
> An API is work in progress right now in order to allow Valkey modules APIs to be called in a safe way from threads

I'm changing this to "Thread safe contexts" with a link to that section in the modules API ref.
