### ISSUE TITLE
`/topics/admin.md` has outdated info

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#96]
In reviewing `/topics/admin.md` for #91, I noticed the following things:

1. References to testing in FreeBSD / OpenBSD / OS X; to my knowledge this testing hasn't be done for Valkey.
2. Antirez's blog is references for "this attack". I think the attack in question really only relevant to Redis 3.2 or below.
3. Under the section "Running Valkey on EC2" it says "Do not use old instance families. For example, use m3.medium with HVM instead of m1.medium with PV." m3 is now a previous generation instance. 
4. It says `CONFIG SET slave-read-only no`

**Comment by zuiderkwast** [comment]
> References to testing in FreeBSD / OpenBSD / OS X; to my knowledge this testing hasn't be done for Valkey.

We have FreeBSD and macOS in our Daily CI.

For the other BSDs in the list, to which we can add NetBSD and DragonFlyBSD, we have had several contributions, so I'm pretty sure we have at least one person that has tested them:

* https://github.com/valkey-io/valkey/pull/462
* https://github.com/valkey-io/valkey/pull/450
* https://github.com/valkey-io/valkey/pull/294
* https://github.com/valkey-io/valkey/pull/293 (This one also touches Solaris and Illumos)

> Antirez's blog is references for "this attack". I think the attack in question really only relevant to Redis 3.2 or below.

Deleting these sentences.

> Under the section "Running Valkey on EC2" it says "Do not use old instance families. For example, use m3.medium with HVM instead of m1.medium with PV." m3 is now a previous generation instance.

Deleting this bullet.

> It says CONFIG SET slave-read-only no

Already fixed in some other PR.
